Unifymodify
dialog-semiconductor/BLE_SDK6_examples pull request #90
Opened 2023-04-11 09:43 UTC by massimilian-89

Hello 
In this PR , The connectivity examples(mostly figures ,some  readme) are being updated. Please let me know if there is a need for further modifications.

2023-04-11 13:31 UTC, NiekIlmer commented on connectivity/Coexistence-example/Readme.md
> +  - Application note for [known hardware limitations for DA14531 devices](https://www.renesas.com/eu/en/document/apn/b-075-da14530531-hardware-guidelines?r=1564826)
```suggestion
  - Application note for [known hardware limitations for DA14531 devices](http://lpccs-docs.renesas.com/sdk6_kll/index.html)
```
This link should probably be to the KLL

2023-04-12 07:56 UTC, koen-vdm requested changes
Nice improvement. some minor updates are needed

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/Coexistence-example/media/DevKit531.svg
the text is streched on this one

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/Coexistence-example/media/DevKit585_586.svg
text is streched

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/active_scanner/Readme.md
> +        * [SDK6 latest version](https://www.renesas.com/eu/en/document/swo/sdk601811821-da1453x-da145856?r=1564826).
If you remove ?r=xxx from the url, it won't break when there is a new release.

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/ble-Midi/Readme.md
> +    - [SDK6 latest version](https://www.renesas.com/eu/en/document/swo/sdk601811821-da1453x-da145856?r=1564826)
If you remove ?r=xxx from the url, it won't break when there is a new release.

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/advertising_example/assets/Motherboard_Hardware_Configuration_DA14531.svg
I think you forgot to remove some pngs in this folder

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/ble-Midi/assets/Motherboard_Hardware_Configuration_DA14531.png
in the original figure there is also a box around J19

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/ble-Midi/assets/Motherboard_Hardware_Configuration_DA14585.svg
missed a square around J19

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/ble_pressure_sensor_bmp388/Readme.md
> +  * [SDK6 latest version](https://www.renesas.com/eu/en/document/swo/sdk601811821-da1453x-da145856?r=1564826).
remove ?r=xx

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/ble_pressure_sensor_bmp388/Readme.md
> +[known hardware limitations for DA1458x devices](https://www.renesas.com/sg/en/document/oth/da1458x-hardware-known-limitations?r=1600291) or [known hardware limitations for DA14531 devices](https://w
remove ?r=xxx

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/ble_pressure_sensor_bmp388/assets/PRO-DK-MikroBus-BMP388.svg
why is the click board in a different socket than the original picture?

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/ble_temperature_ntf/Readme.md
> +- [SDK6 latest version](https://www.renesas.com/eu/en/document/swo/sdk601811821-da1453x-da145856?r=1564826).
remove ?r=xxx

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/ble_temperature_ntf/assets/basic.svg
this is stull just a picture? was there no svg available?

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/ble_temperature_ntf/assets/da14531_temp.svg
clickboard moved to different socket

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/central/Readme.md
> +        * [SDK6 latest version](https://www.renesas.com/eu/en/document/swo/sdk601811821-da1453x-da145856?r=1564826), Older versions of SDK6 require minimal changes.
remove ?r=xxx

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/simple_beacon/Readme.md
> +  - [SDK6.0.18](https://www.renesas.com/eu/en/document/swo/sdk601811821-da1453x-da145856?r=1564826) or later
remove ?r=xxx

2023-04-12 07:56 UTC, koen-vdm commented on connectivity/switching_roles/Readme.md
> +- [SDK6 latest version](https://www.renesas.com/sg/en/document/swo/sdk601811821-da1453x-da145856?r=1564826)
remove ?r=xxx

2023-04-20 09:49 UTC, massimilian-89 commented
Guy I am done here please review and give me the hints

2023-04-21 09:09 UTC, koen-vdm requested changes
Some issues I pointed out last review are still present. and a question is still unanswered

2023-04-24 09:11 UTC, koen-vdm approved these changes

2023-04-24 09:44 UTC, NiekIlmer approved these changes

2023-04-24 09:44 UTC, merged